//1
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("0.17.0.1")]
[assembly: AssemblyVersion("0.17.0.0")]

namespace Notes
{
	public static class Version
	{
		public const int major = 0;
		public const int minor = 17;
		public const int patch = 0;
		public const int build = 0;
		public const string Number = "0.17.0.0";
#if DEBUG
        public const string Text = Number + "-zed'K BETA DEBUG";
#else
        public const string Text = Number + "-zed'K";
#endif
	}
}